feat: react base action

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -1,34 +1,109 @@
-name: "Deploy in Windows server"
-description: "Deploy in windows server"
+name: "React Continuos Integration"
+description: "Realiza el lint, build, test and coverage"
 inputs:
-  registry:
-    description: "Container Registry"
+  matrix_version:
+    description: "matrix de pruebas node"
+    required: true
+  fontawesome_token: 
+    description: "token de fontawesome"
     required: false
-    default: 'ghcr.io'
-  username:
-    description: "Username for Container Registry"
-    required: true
-  password:
-    description: "token or password for container registry"
-    required: true
+    default: ''
+  packages_token:
+    description: "token github para autenticarse en packages"
+    required: false
+    default: ''
+  skip_test:
+    description: "permite skipear los procesos de testing"
+    required: false
+    default: 'false' 
+  ci:
+    description: "Esta variable forza el chequeo del linter y en caso de fallas rompe el flujo"
+    required: false
+    default: 'false'
 runs:
   using: "composite"
   steps:
-    - uses: actions/checkout@v3
-    #- name: Login to GitHub Container Registry
-    #  uses: redhat-actions/podman-login@v1
-    #  with:
-    #    registry: ${{ inputs.registry }} 
-    #    username: ${{ inputs.username }}
-    #    password: ${{ inputs.password }}
-    - name: Podman login
-      run: sudo podman login -u ${{ inputs.username }} -p ${{ inputs.password }} ${{ inputs.registry }} 
-      shell: bash
-    - name: Restart compose
-      run: sudo podman-compose down
-      shell: bash
-    - name: deploy and run
+    - name: Get package manager of Repo
+      env:
+        ENABLE_TEST_COMMENTS: ${{ inputs.skip_test != 'true' && github.event_name == 'pull_request' && github.actor != 'dependabot[bot]' }}
       run: |
-        sudo podman-compose pull 
-        sudo podman-compose up -d
+        if [ -f "yarn.lock" ]; then 
+          echo "name=yarn" >> $GITHUB_OUTPUT
+        elif [ -f "package-lock.json" ]; then 
+          echo "name=npm" >> $GITHUB_OUTPUT 
+        elif [ -f pnpm-lock.yaml ]; then 
+          echo "name=pnpm" >> $GITHUB_OUTPUT 
+        else 
+          echo "name=notfound" >> $GITHUB_OUTPUT  
+        fi
+      id: package_manager
       shell: bash
+    - name: validate 'Lockfile'
+      if: ${{ steps.package_manager.outputs.name == 'notfound' }}
+      run: |
+        echo "El código debe contener algún archivo de lockfile ('package-lock.json', 'yarn.lock' o 'pnpm-lock.yaml')."
+        echo "Asegurate de subirlo."
+        echo "ERROR: Falta archivo lockfile. Ver más en https://architecture-it.github.io/docs/Platform/Front/#manejo-de-dependencias"
+        exit 1
+      shell: bash    
+      # Use default with cache
+    - name: Use pnpm Setup
+      uses: pnpm/action-setup@v2
+      with:
+        version: 6.32.9
+      if: ${{ steps.package_manager.outputs.name == 'pnpm' }}
+    - name: Use Node.js ${{ inputs.matrix_version }} - Cache ${{ steps.package_manager.outputs.name }}
+      uses: actions/setup-node@v3
+      with:
+        node-version: ${{ matrix.node-version }}
+        cache: ${{ steps.package_manager.outputs.name }}
+    - name: config npmrc file fontawesome 
+      run: |
+        echo '@fortawesome:registry=https://npm.fontawesome.com/' >> .npmrc
+        echo '//npm.fontawesome.com/:_authToken=${{ inputs.fontawesome_token }}' >> .npmrc
+      shell: bash
+      if: ${{ inputs.fontawesome_token != '' }}
+    - name: config npmrc file github packages of company
+      run: |
+        echo '@customer-experience:registry=https://npm.pkg.github.com/' >> .npmrc
+        echo '@architecture-it:registry=https://npm.pkg.github.com/' >> .npmrc
+        echo '@operations-innovation:registry=https://npm.pkg.github.com/' >> .npmrc
+        echo '//npm.pkg.github.com/:_authToken=${{ inputs.packages_token }}' >> .npmrc
+      shell: bash
+      if: ${{ inputs.packages_token != '' }}
+    - name: Install dependencies
+      run: |
+        if [ -f yarn.lock ]; then 
+          yarn --frozen-lockfile
+        elif [ -f package-lock.json ]; then
+          npm ci --no-progress --loglevel error
+        elif [ -f pnpm-lock.yaml ]; then
+          yarn global add pnpm && pnpm install --frozen-lockfile
+        fi
+      shell: bash
+    - name: Lint
+      run: ${{ steps.package_manager.outputs.name }} run lint --if-present
+      shell: bash
+    - name: Build
+      run: ${{ steps.package_manager.outputs.name }} run build
+      shell: bash
+      env:
+        CI: ${{ inputs.ci == 'true' }}
+    - run: ${{ steps.package_manager.outputs.name }} test -- --json --coverage --runInBand --testLocationInResults --outputFile=report.json
+      name: Unit tests
+      shell: bash
+      env:
+        CI: ${{ inputs.ci == 'true' }}
+      if: ${{ inputs.skip_test != 'true' }}
+    - name: Coverage reporter
+      uses: ArtiomTr/jest-coverage-report-action@v2
+      id: coverage-reporter
+      with:
+        output: report-markdown
+        skip-step: all
+      if: ${{ env.ENABLE_TEST_COMMENTS }}
+    - name: Coverage reporter Comment
+      uses: marocchino/sticky-pull-request-comment@v2
+      with:
+        message: ${{ steps.coverage-reporter.outputs.report }}
+      if: ${{ env.ENABLE_TEST_COMMENTS }}
